
# TODO write compose of our services.

# Example File added 03/03

version: '3'

services:
  spark-master:
    image: myspark/sparkcontainer:v0 # Spark Image
    container_name: spark-master
    ports:
      - "8080:8080"   # Spark Master UI
      - "7077:7077"   # Spark Master Port
    command: /usr/local/spark/sbin/start-master.sh # Start Master; assigns role

# TODO: Add more workers to the cluster when we know it works with one worker
  spark-worker:
    image: myspark/sparkcontainer:v0 # Spark Image (Note: its the same for both master and worker)
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    command: /usr/local/spark/sbin/start-worker.sh spark://spark-master:7077 # Start Worker; assigns role 
